sslworld: project airbone balls
RoboCup-SSL/grSim pull request #138
Opened 2021-01-19 17:12 UTC by tobiasheineken

### Identify the Bug
[131](https://github.com/RoboCup-SSL/grSim/issues/131)

### Description of the Change

In ssl-vision, balls are always projected onto the field (see bugreport).

While ssl-vision already corrects these positions for the height of the ball itself, this correct is no longer correct as soon as the ball is being chipped.

In order to emulate ssl-visions behavior and make grSim closer to realitiy, we need to trace a ray from the camera to the ball.
The location where this ray would hit the field (corrected by the radius of the ball itself) will be reported by ssl-vision.

This distortion fails as soon as the ball is almost the same height as the camera itself. While the correct approach would be to not show the ball in these cases, I decided on simply bounding the height of the ball (subtracted its already corrected radius) by SCALING_FACTOR * camera_height. This should be correct for sufficiently large camera_heights, as airborne balls normally don't reach the camera.

As already stated in the commit description, this commit / PR does not include the option to enable / disable this feature via UI. While the code is already ready to get a boolean somewhere and use that boolean to decide if a projection is needed, I have no idea how to properly interact with the UI to get a boolean like that. Instead, it uses a constant that can be modified to get the old behavior.

### Alternate Designs

It would have been more correct to discard balls with ball.z ~ camera.z or ball.z > camera.z. As already stated, I don't think that happens particularly often and the boding right now is just to prevent dividing by ~0 in very rare cases (bugs?)

### Possible Drawbacks

Using and publishing the real, correct positions instead of distorting them onto a 2d plane makes it easier for teams to locate the ball. However, as a simulation is only as good as its mapping in reality, having a superoptimal simulator has very little use for advanced teams.

Having a UI Option instead of flicking a bool in the source code would be nice, but I have no Idea how to properly do that. 

### Verification Process

Follow more or less the process outlined in [131](https://github.com/RoboCup-SSL/grSim/issues/131).

You can see that the ball no longer follows a line. Also, if you're able to see the reported packages (i.e. by using protobufs ->DebugString and writing that to stdout), you can see there's no longer a z-coordinate published by grSim.

### Release Notes

More realistic reporting of airborne balls

2021-01-20 06:01 UTC, mahi97 requested changes
Thanks a lot, @tobiasheineken, for the good description and well implementation. I also believe this feature will greatly help many teams to be more prepared for the real world.

I would appreciate it if you apply minor fixes for consistency fo configuration, then we can merge this PR.

2021-01-20 07:47 UTC, tobiasheineken commented on src/sslworld.cpp
> +    const float CAMERA_HEIGHT = 4;
Note that I didn't create this constant, neither the focal_length constant. I just moved it. I can still try to move them into the UI.

2021-01-20 07:59 UTC, mahi97 commented on src/sslworld.cpp
> +    const float CAMERA_HEIGHT = 4;
I see. I still believe it will improve the code quality, so why not.

2021-01-21 17:56 UTC, tobiasheineken commented on src/sslworld.cpp
> +            const float SCALING_LIMIT = 0.9;
I don't really think teams are going to understand these values (scaling limit and focal length). But I've added them nonetheless, see the newest commit.

2021-01-22 01:37 UTC, mahi97 approved these changes
Great Job!
Thanks

2021-01-22 01:37 UTC, merged