WIP: Stop the robots when the stop receiving packages for 1 sec
RoboCup-SSL/grSim pull request #168
Opened 2021-10-02 04:28 UTC by Bollos00

### Identify the Bug

Closes #166 

### Description of the Change

* Whenever a socket is received from `blueControlSocket`, the `QElapsedTimer` `elapsedLastPackageBlue` is restarted.
* The function `MainWindow::update` will check every time it is called if `elapsedLastPackageBlue` has not been restarted for more than one second. If the condition is true, it will stop all blue robot. A similar/equivalent approach was made for the `yellowControlSocket`.

### Alternate Designs

Nothing.

### Possible Drawbacks

* It does not turn the roller and the kick (I still did not find the proper way of doing so);
* I am still testing it.

### Verification Process

### Release Notes

Stop the robots when the stop receiving packages for 1 second

2021-10-03 03:01 UTC, Bollos00 commented
@mahi97 I tested it with a match test and I think this pull request is ready for review now.

One question, should I change something on the piece of code complained bu the CodeFactor?

2022-02-14 06:46 UTC, Bollos00 commented
@g3force this pull request is open for quite some time now... do I need to change anything before the pull request is merged?

2022-02-14 08:26 UTC, g3force requested changes
Looks good to me except for the comments.

2022-02-14 08:26 UTC, g3force commented on src/mainwindow.cpp
> +//                glwidget->ssl->robots[index]->kicker->setRoller(0);
Why is this commented out?

2022-02-14 08:26 UTC, g3force commented on src/mainwindow.cpp
> +                    continue;
Some `{}` would be nice here, as the `if` is already on two lines

2022-02-14 19:52 UTC, Bollos00 commented on src/mainwindow.cpp
> +//                glwidget->ssl->robots[index]->kicker->setRoller(0);
I was testing and forgot to remove it.

2022-02-17 02:22 UTC, Bollos00 commented
@g3force what about now?

2022-02-17 08:20 UTC, g3force commented
I've fixed the pipelines on master und updated your branch to see if everything is green.

Also, please use the GitHub review functions:
![image](https://user-images.githubusercontent.com/779094/154434296-0b6e7d06-34cf-4918-b118-0f9e2442a2ae.png)

Press the cyclic arrows to rerequest review.

2022-02-17 08:22 UTC, g3force commented
And please fix the CodeFactor issue. One method you modified is too complex now. Move code into a new method.

2024-01-03 18:47 UTC, g3force approved these changes

2024-01-03 18:48 UTC, merged